theme: jekyll-theme-al-folio
title: Technical Writer and Manager Portfolio
description: Showcase of technical writing work and publications on managing technical writing projects and technical writers.
