theme: jekyll-theme-minimal
title: Technical Writer and Manager Portfolio
description: Showcase of technical writing work and publications on managing technical writing projects and technical writers.
